name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.6.0
        with:
          # Path to the local folder you want to copy.
          local: ./index.html
          # Path on the remote server to copy to.
          remote: /var/www/html/index.html

          # Hostname or IP address of the server.
          host: ${{ secrets.REMOTE_HOST }}
          # Username for authentication.
          username: ${{ secrets.REMOTE_USER }}

          # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          # Password for password-based user authentication.
          password: ${{ secrets.REMOTE_PASS }}
